---
- name: test
  hosts: localhost
  tasks:
    - name: Debug ipv4 addresses
      debug: 
        var: ansible_facts['all_ipv4_addresses']
    - name: Get interfaces
      debug: 
        var: ansible_facts['interfaces']
    - name: Copy dotfiles
      copy:
        src: "./{{ item }}"
        dest: "~/.{{ item }}"
      loop:
        - zshrc
        - vimrc
        - gvimrc
        
